title: Claude Helper
description: Enhance your Claude AI experience with bulk uploads and quick resets
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
github:
  is_project_page: true
  versions_url: changelog.html
favicon: assets/images/claudehelper128x128.png
